name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
      - name: Build
        run: ./mvnw -B package -DskipTests --file pom.xml
      - name: Test
        run: ./mvnw -B test --file pom.xml